routes/web.php
		Route::resource('admin/userrole', 'MRoleController');
		Route::get('admin/userrole/trash/deleted', 'MRoleController@trash');
		Route::get('admin/userrole/restore/{id}', 'MRoleController@restore');
		Route::get('admin/userrole/deletepermanent/{id}', 'MRoleController@permanentDelete');

		//ListUserAdmin
		Route::resource('admin/user', 'MUserController');
		Route::get('user/api/user', 'MUserController@apiUser');
	});

	Route::middleware(['produk'])->group(function () { });

	//Transaksi
	Route::middleware(['transaksi'])->group(function () { });

	Route::middleware(['approval'])->group(function () {
		Route::get('/admin/approval/info', 'PostController@indexApprovalInfo');
		Route::get('/admin/approval/info/{id}/edit', 'PostController@editApprovalInfo');
		Route::get('/admin/approval/info/{id}/show', 'PostController@showApprovalInfo');
		Route::post('/admin/approval/info/{id}', 'PostController@updateApprovalInfo');
		Route::get('/admin/approval/info/{id}/approve', 'PostController@approveApprovalInfo');
		Route::get('/admin/approval/info/{id}/delete', 'PostController@deleteApprovalInfo');
		Route::get('/admin/api/approval/info', 'PostController@apiApprovalInfo');

		Route::get('/admin/approval/artikel', 'PostController@indexApprovalArtikel');
		Route::get('/admin/approval/artikel/{id}/edit', 'PostController@editApprovalArtikel');
		Route::get('/admin/approval/artikel/{id}/show', 'PostController@showApprovalArtikel');
		Route::post('/admin/approval/artikel/{id}', 'PostController@updateApprovalArtikel');
		Route::get('/admin/approval/artikel/{id}/approve', 'PostController@approveApprovalArtikel');
		Route::get('/admin/approval/artikel/{id}/delete', 'PostController@deleteApprovalArtikel');
		Route::get('/admin/api/approval/artikel', 'PostController@apiApprovalArtikel');

		Route::get('/admin/approval/kronik', 'PostController@indexApprovalKronik');
		Route::get('/admin/approval/kronik/{id}/edit', 'PostController@editApprovalKronik');
		Route::get('/admin/approval/kronik/{id}/show', 'PostController@showApprovalKronik');
		Route::post('/admin/approval/kronik/{id}', 'PostController@updateApprovalKronik');
		Route::get('/admin/approval/kronik/{id}/approve', 'PostController@approveApprovalKronik');
		Route::get('/admin/approval/kronik/{id}/delete', 'PostController@deleteApprovalKronik');
		Route::get('/admin/api/approval/kronik', 'PostController@apiApprovalKronik');
	});

	Route::middleware(['kontributor'])->group(function () {

		Route::get('/admin', 'HomeController@index')->name('admin');
		Route::get('/home', 'HomeController@index')->name('home');
		Route::get('/admin/get-new-count/{id?}', 'HomeController@tableCount');
		Route::get('/admin/profile/{id}', 'HomeController@profile');

		Route::get('/admin/artikel', 'PostController@indexArtikel');
		Route::get('/admin/artikel/create', 'PostController@createArtikel');
		Route::get('/admin/artikel/{id}/edit', 'PostController@editArtikel');
		Route::get('/admin/artikel/{id}/show', 'PostController@showArtikel');
		Route::post('/admin/artikel/', 'PostController@storeArtikel');
		Route::post('/admin/artikel/{id}', 'PostController@updateArtikel');
		Route::get('/admin/artikel/{id}/send-approval', 'PostController@approvalArtikel');
		Route::get('/admin/artikel/{id}/delete', 'PostController@deleteArtikel');
		Route::get('/admin/api/artikel', 'PostController@apiArtikel');

		Route::get('/admin/kronik', 'PostController@indexKronik');
		Route::get('/admin/kronik/create', 'PostController@createKronik');
		Route::get('/admin/kronik/{id}/edit', 'PostController@editKronik');
		Route::get('/admin/kronik/{id}/show', 'PostController@showKronik');
		Route::post('/admin/kronik/', 'PostController@storeKronik');
		Route::post('/admin/kronik/{id}', 'PostController@updateKronik');
		Route::get('/admin/kronik/{id}/send-approval', 'PostController@approvalKronik');
		Route::get('/admin/kronik/{id}/delete', 'PostController@deleteKronik');
		Route::get('/admin/api/kronik', 'PostController@apiKronik');

		Route::get('/admin/info', 'PostController@indexInfo');
		Route::get('/admin/info/create', 'PostController@createInfo');
		Route::get('/admin/info/{id}/edit', 'PostController@editInfo');
		Route::get('/admin/info/{id}/show', 'PostController@showInfo');
		Route::post('/admin/info/', 'PostController@storeInfo');
		Route::post('/admin/info/{id}', 'PostController@updateInfo');
		Route::get('/admin/info/{id}/send-approval', 'PostController@approvalInfo');
		Route::get('/admin/info/{id}/delete', 'PostController@deleteInfo');
		Route::get('/admin/api/info', 'PostController@apiInfo');
	});

	Route::resource('admin/proposal', 'ProposalController');
	Route::get('admin/proposal-pengajuan/{pengajuan?}', 'ProposalController@index')->name('proposal.submission');
	Route::get('admin/proposal/create/upload', 'ProposalController@upload')->name('proposal.upload');
	Route::match(['GET', 'POST'], 'admin/proposal-note/{id}', 'ProposalController@note')->name('proposal.note');
	Route::get('admin/proposal/{id}/signaturre', 'ProposalController@addSignature')->name('proposal.signature');
	Route::get('proposal-signature/{id}', 'ProposalController@signatureReject')->name('proposal.signature.reject');
	Route::post('admin/proposal-signature', 'ProposalController@addSignaturePost')->name('proposal.signature.post');
	Route::get('admin/proposal-download/{id}', 'ProposalController@download')->name('proposal.download');

	Route::resource('admin/lpj', 'LPJController');
	Route::get('admin/proposal-lpj/{pengajuan?}', 'LPJController@index')->name('lpj.submission');
	Route::get('admin/lpj/create/upload', 'LPJController@upload')->name('lpj.upload');
	Route::match(['GET', 'POST'], 'admin/lpj-note/{id}', 'LPJController@note')->name('lpj.note');
	Route::get('admin/get-agenda/{id}', 'LPJController@getAgenda');
	Route::get('admin/lpj/{id}/signature', 'LPJController@addSignature')->name('lpj.signature');
	Route::get('lpj-signature/{id}', 'LPJController@signatureReject')->name('lpj.signature.reject');
	Route::post('admin/lpj-signature', 'LPJController@addSignaturePost')->name('lpj.signature.post');
	Route::get('admin/lpj-download/{id}', 'LPJController@download')->name('lpj.download');


	//Sakramen

	//Sakramen Nikah,Baptis,Komuni, Transaksi Sakramen
	Route::get('/admin/sakramen/{tsakramen}/{typebaptis?}', 'SakramenController@index');
	Route::get('/admin/sakramen_ttd/{tsakramen}/{typebaptis?}', 'SakramenController@indexTtd')->name('sakramenttd.index');
	Route::get('/admin/sakramen-create/{tsakramen}/{typebaptis?}', 'SakramenController@create');
	Route::post('/admin/sakramen-store', 'SakramenController@store');
	Route::get('/admin/sakramen-edit/{tsakramen}/{id}/{typebaptis?}', 'SakramenController@edit');
	Route::put('/admin/sakramen-update/{id}', 'SakramenController@store');
	Route::get('/admin/sakramen-delete/{tsakramen}/{id}', 'SakramenController@delete');
	Route::get('admin/skn-upto/{model}/{id}', 'SakramenController@toInApproval')->name('skn.upto');
	Route::get('skn-upto-by-admin/{model}/{id}/{setstatus}', 'SakramenController@toUp')->name('skn.upto');
	Route::get('/admin/tahapan-sakramen/{type}', 'SakramenController@tahapan');
	Route::post('/admin/tahapan-image/{id}/{type}', 'SakramenController@updateImage');
	Route::get('/admin/tahapan-image-delete/{id}', 'SakramenController@deleteImage');
	Route::get('/sakramen-report', 'SakramenController@reportTransaction');
	Route::post('/sakramen-report', 'SakramenController@applyFilterReport');

	Route::get('admin/sakramen-signature/{id}/{tsakramen}/{tbaptis?}', 'SakramenController@addSignature')->name('sakramen.signature');
	Route::post('admin/sakramen-signature', 'SakramenController@addSignaturePost')->name('sakramen.signature.post');
	Route::get('admin-sakramen-print/{type}/{id}/printout', 'SakramenController@download')->name('sakramen.download');

	Route::get('sakramen-signature-ummat/{id}/{tsakramen}/{tbaptis?}', 'SakramenController@addSignatureUmmat')->name('sakramen.signature');
	Route::post('sakramen-signature-ummat', 'SakramenController@ummatSignature')->name('sakramen.signature-ummat.post');


	Route::get('admin/transaksi-sakramen', 'SakramenController@trx');




	// Route::resource('/admin/record-ummat', 'RecordUmmatController');
	Route::get('/admin/pencatatan-{type}', 'RecordUmmatController@index')->name('pencatatan.index');
	Route::get('/admin/pencatatan-{type}/create', 'RecordUmmatController@create')->name('pencatatan.create');
	Route::post('/admin/pencatatan-{type}', 'RecordUmmatController@store')->name('pencatatan.store');
	Route::get('/admin/pencatatan-{type}/{id}/edit', 'RecordUmmatController@edit')->name('pencatatan.edit');
	Route::put('/admin/pencatatan/{id}/update', 'RecordUmmatController@update')->name('pencatatan.update');
	Route::delete('/admin/pencatatan/{id}', 'RecordUmmatController@destroy')->name('pencatatan.destroy');
});


Route::get('upline-user/{id}/{type}', 'MUserController@sendEmail');
Route::get('ttd_umat', 'SakramenController@ttdUmat');
Route::get('download-tahapan/{id}', function($id)
{
	// dd($filename);
	$getFile = \DB::table('m_tahapan_image')->where('id',$id)->first();

    // Check if file exists in app/storage/file folder
    $file_path = public_path() .'/upload/tahapan/'. $getFile->image_tahapan;
    if (file_exists($file_path))
    {
        // Send Download
        return \Response::download($file_path, $getFile->image_tahapan, [
            'Content-Length: '. filesize($file_path)
        ]);
    }
    else
    {
        // Error
        exit('Requested file does not exist on our server!');
    }
});

Route::get('view-image/{filename}', function ($filename)
{
    $path = public_path('upload/tahapan/' . $filename);

    if (!File::exists($path)) {
        return response()->json('file tidak ditemukan', 404);
    }
    $file = File::get($path);
    $type = File::mimeType($path);

    $response = Response::make($file, 200);
    $response->header("Content-Type", $type);

    return $response;
});

app/Models/LPJ.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class LPJ extends Model
{
    protected $table = 'lpj';

    protected $guarded = ['id'];

    //relations
    public function budget_in()
    {
        return $this->hasMany(\App\Models\LPJBudgetIn::class, 'lpj_id', 'id');
    }

    public function budget_out()
    {
        return $this->hasMany(\App\Models\LPJBudgetOut::class, 'lpj_id', 'id');
    }

    // public function temp_agenda()
    // {
    //     return $this->hasMany(\App\Models\LPJTempAgenda::class, 'lpj_id', 'id');
    // }

    public function signature()
    {
        return $this->hasMany(\App\Models\LPJSignature::class, 'lpj_id', 'id');
    }


    public static function boot()
    {
        parent::boot();

        static::deleting(function ($pro) { // before delete() method call this
            $pro->budget_in()->delete();
            $pro->budget_out()->delete();
            $pro->signature()->delete();
        });
    }
}

resources/views/admin/posting/lpj/_actions.blade.php
{{-- <span href="{{ $links['show'] }}" class="btn btn-default btn-xs" title="{{ucwords($data->judul)}}"><span class="fa fa-eye"></span></span> --}}
@if($data->status == 'pending')
    @if($user->id == $data->user_id)
        <a href="{{ $links['edit'] }}" class="btn btn-default btn-xs" title="{{ucwords($data->judul)}}"><span class="fa fa-edit"></span></a>

        <a href="{{ route('lpj.upstatus',['oldstatus' => $data->status,'id' => $data->id, 'change' => 'in-approval']) }}"
            class="btn btn-primary btn-xs" title="send to in-approval {{ucwords($data->judul)}}?">
            <span class="fa fa-send"></span>
        </a>
        <a href="{{ $links['destroy'] }}" class="btn btn-danger btn-xs postback" title="Hapuss {{ucwords($data->judul)}}?"><span class="fa fa-trash"></span></a>
    @else
        -
    @endif
@elseif($data->status == 'in-approval')
    @if(in_array($user->role,[1,2]))
        <a href="{{ route('lpj.upstatus',['oldstatus' => $data->status,'id' => $data->id, 'change' => 'approved']) }}"
            class="btn btn-success btn-xs btn-approved" title="approve {{ucwords($data->judul)}}?">
            <span class="fa fa-check"></span>
        </a>

        <a href="{{ route('lpj.upstatus',['oldstatus' => $data->status,'id' => $data->id, 'change' => 'cancel']) }}"
            class="btn btn-danger btn-xs" title="cancel {{ucwords($data->judul)}}?">
            <span class="fa fa-close"></span>
        </a>
    @else
    -
    @endif
@elseif($data->status == 'approved')
    <a href="{{ route('lpj.note',['id' => $data->id]) }}"
        class="btn btn-primary btn-xs" title="Catatan {{ucwords($data->judul)}}?">
        <span class="fa fa-book"></span>
    </a>

    <a href="{{ route('lpj.signature',['id' => $data->id]) }}"
        class="btn btn-default btn-xs" title="Tanda Tangan {{ucwords($data->judul)}}?">
        <span class="fa fa-signature"></span>
    </a>

    <a href="{{ route('lpj.signature.reject',['id' => $data->id]) }}"
        class="btn btn-danger btn-xs" title="Reject {{ucwords($data->judul)}}?">
        <span class="fa fa-close"></span>
    </a>
@else
-
@endif

@if($data->type == 'upload' )
    <a href="{{ route('lpj.download',$data->id) }}" download=""
        class="btn btn-default btn-xs" title="download {{ucwords($data->judul)}}?">
        <span class="fa fa-arrow-down"></span>
    </a>
@endif

resources/views/admin/posting/lpj/index.blade.php
@extends('app')

@section('treeview_post','active')
@section('treeview_lpj','active')

@section('title', 'LPJ')
@section('contentheader_title', 'LPJ')

@section('customcss')
<link rel="stylesheet" href="{{ URL::asset('css/datatables.min.css') }}">
@stop

    @section('main-content')
    <div class="box box-primary">
        <div class="box-header">
            <h3 class="box-title">LPJ  {{ ($type == 'submission') ? 'Pengajuan' : '' }}</h3>
            <div class="box-tools pull-right">
                @if(Auth::user()->role == 3)
                    @php $katUser = \DB::table('m_kategori_user')->where('id_kategori_user',Auth::user()->id_header_user)->first(); @endphp
                        @if(!in_array($katUser->type,['romo','wilayah','bidang']))
                            <a href="{{ route('lpj.create') }}" class="btn btn-success btn-sm">
                                <i class="fa fa-plus"></i> Tambah Data
                            </a>
                            <a href="{{ route('lpj.upload') }}" class="btn btn-primary btn-sm">
                                <i class="fa fa-file"></i> Upload
                            </a>
                        @endif
                @else
                    <a href="{{ route('lpj.create') }}" class="btn btn-success btn-sm">
                        <i class="fa fa-plus"></i> Tambah Data
                    </a>
                    <a href="{{ route('lpj.upload') }}" class="btn btn-primary btn-sm">
                        <i class="fa fa-file"></i> Upload
                    </a>
                @endif
                <a href="{{ route('lpj.index') }}" class="btn btn-default btn-sm">
                    <i class="fa fa-list"></i> LPJ
                </a>

                <a href="{{ route('lpj.submission','submission') }}" class="btn btn-warning btn-sm">
                    <i class="fa fa-signature"></i> Pengajuan
                </a>
            </div>
        </div>
        <div class="box-body">
            <table class="table table-striped table-hover table-responsive" id="table" style="width: 100%;">
                <thead>
                    <tr>
                        <th>No.</th>
                        <th>Judul</th>
                        <th>Dibuat</th>
                        <th>Tanggal</th>
                        <th>Type</th>
                        <th>Status</th>
                        <th class="nosort">Aksi</th>
                    </tr>
                </thead>
                <tbody>

                </tbody>
            </table>
        </div>
    </div>
    @endsection

    @section('customscript')
    <script type="text/javascript"
        src="{{ URL::asset('plugins/datatables/jquery.dataTables.min.js') }}"></script>
    <script type="text/javascript"
        src="{{ URL::asset('plugins/datatables/dataTables.bootstrap.min.js') }}"></script>

    <script type="text/javascript">
        var user = "{{ Auth::user()->id }}";
        $(document).ready(function () {
            $('#table').DataTable({
                'paging': true,
                'lengthChange': true,
                'searching': true,
                'ordering': true,
                'info': true,
                'autoWidth': false,
                "language": {
                    "emptyTable": "Data Kosong",
                    "info": "Menampilkan _START_ sampai _END_ dari _TOTAL_ data",
                    "infoEmpty": "Menampilkan 0 sampai 0 dari 0 data",
                    "infoFiltered": "(disaring dari _MAX_ total data)",
                    "search": "Cari:",
                    "lengthMenu": "Tampilkan _MENU_ Data",
                    "zeroRecords": "Tidak Ada Data yang Ditampilkan",
                    "oPaginate": {
                        "sFirst": "Awal",
                        "sLast": "Akhir",
                        "sNext": "Selanjutnya",
                        "sPrevious": "Sebelumnya"
                    },
                },

                processing: true,
                serverSide: true,
                ajax: '<?= url("/api/lpj") ?>/'+user+"/{{$type}}",
                columns: [
                    { data: 'DT_Row_Index', name: 'DT_Row_Index',searchable: false, orderable: false },
                    { data: 'judul', name: 'lpj.judul' },
                    { data: 'createuser', name: 'lpj.createuser' },
                    { data: 'created_at', name: 'lpj.created_at' },
                    { data: 'type', name: 'lpj.type' },
                    { data: 'status', name: 'status' },
                    { data: 'action', name: 'action', orderable: false, searchable: false }
                ]
            });
        });
    </script>
    @stop

resources/views/admin/posting/lpj/upload.blade.php
@extends('app')

@section('treeview_post','active')
@section('treeview_lpj','active')

@section('title', 'Upload LPS')

@section('customcss')
<link rel="stylesheet" href="{{ URL::asset('css/datatables.min.css') }}">
<link rel="stylesheet" href="{{ URL::asset('/plugins/select2/select2.min.css') }}">
<link href="{{ asset('plugins/select2/select2-bootstrap.min.css') }}" rel="stylesheet" />
<link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.css" rel="stylesheet">
@stop

    @section('contentheader_title', 'Upload LPJ')

    @section('main-content')

    <div class="row">
        <div class="col-md-12">
            <!-- form start -->
            <form method="post" enctype="multipart/form-data" onsubmit="return cekBalance();"
            action="@if(!isset($editmode)){{route('lpj.store')}}@else{{route('lpj.update',$id)}}@endif">
                <!-- /.box-header -->
                <div class="box box-primary">
                    {{ csrf_field() }} @if(!isset($editmode)) @method('POST') @else  @method('PUT') @endif
                    <div class="box-body" style="margin-left: 20px;">
                        <div class="row">
                            <div class="form-group col-md-6">
                                <label for="">Judul LPJ <span class="required">*</span></label>
                                <input type="text"
                                    class="form-control{{ $errors->has('judul') ? ' is-invalid' : '' }}"
                                    name="judul" id="judul" value="{{ old('judul') }}"
                                    placeholder="judul...">
                                @if($errors->has('judul'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('judul') }}</strong>
                                    </span>
                                @endif
                            </div>

                            <div class="form-group col-md-6 @if($editmode) has-warning @endif"">
                                <label for="">file <span class="required">*</span></label>
                                <input type="file"
                                class="form-control{{ $errors->has('file_upload') ? ' is-invalid' : '' }}" name="file_upload" id="file_upload"
                                    value="{{ old('file_upload') }}" placeholder="kegiatan...">
                                @if($errors->has('file_upload'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('file_upload') }}</strong>
                                    </span>
                                @endif
                                @if ($editmode)
                                    <span class="help-block">Timpa File yang sudah terupload?</span>
                                @endif
                            </div>
                        </div>

                        <div class="row">
                            <label for="">Rencana Anggaran</label>
                            <table class="table table-bordered" id="table-pemasukan">
                                <thead>
                                    <th>
                                        <button type="button" class="btn btn-xs btn-success"
                                            title="Tambah Data Pengeluaran" onclick="addRow('table-pemasukan')">
                                            <span class="fa fa-plus"></span>
                                        </button>
                                    </th>
                                    <th>Pemasukan</th>
                                    <th>Total</th>
                                </thead>
                                <tbody>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tbody>
                                <tfoot>
                                    {{-- <td></td> --}}
                                    <td colspan="2" style="text-align:right">Jumlah : </td>
                                    <td>
                                        <input type="text" class="form-control input-sm" id="jmlpem" readonly value="0"
                                            style="text-align:right">
                                    </td>
                                </tfoot>
                            </table>

                            <table class="table table-bordered" id="table-pengeluaran">
                                <thead>
                                    <th>
                                        <button type="button" class="btn btn-xs btn-success"
                                            title="Tambah Data Pengeluaran" onclick="addRow('table-pengeluaran')">
                                            <span class="fa fa-plus"></span>
                                        </button>
                                    </th>
                                    <th>Pengeluaran</th>
                                    <th>Nominal</th>
                                    <th width="15%">Rincian</th>
                                    <th>Total</th>
                                </thead>
                                <tbody>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                    <td></td>
                                </tbody>
                                <tfoot>
                                    <td style="text-align:right" colspan="4">Jumlah : </td>
                                    <td>
                                        <input type="text" class="form-control input-sm" id="jmlpeng" readonly value="0"
                                            style="text-align:right">
                                    </td>
                                </tfoot>
                            </table>
                        </div>

                        <hr>

                        <div class="row">
                            <div class="form-group col-md-10 col-md-offset-1">
                                <label for="">Catatan <span class="required">*</span></label>
                                <textarea name="note" id="note"
                                    class="form-control{{ $errors->has('note') ? ' is-invalid' : '' }} summernote">{{ old('note') }}</textarea>
                                @if($errors->has('form'))
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $errors->first('note') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                    </div>
                    <div class="box-footer">
                        <div class="pull-right">
                            <a href="{{ url('/admin/kronik') }}" class="btn btn-info">Kembali</a>
                            <input type="reset" class="btn btn-danger" id="reset" value="Batal">
                            <input type="submit" class="btn btn-success" value="Simpan">
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    @endsection
    @section('customscript')
    <script type="text/javascript"
        src="{{ URL::asset('/plugins/select2/select2.full.min.js') }}"></script>
    <script type="text/javascript" src="{{ URL::asset('/plugins/mask/mask.js') }}"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.12/summernote.js"></script>
    <script type="text/javascript">

        @isset($editmode)
            var data = {!! $data !!};
            callBackData(data);
        @endif

        $(".select2").select2();
        $('.price').mask('000.000.000', {
            reverse: true
        });

        $('.summernote').summernote({
            height: 150,
            toolbar: [
                ['style', ['bold', 'italic', 'underline', 'strikethrough']],
                ['fontsize', ['fontsize', 'height', 'hr']],
                ['para', ['ul', 'ol', 'paragraph']],
                ['table', ['table']],
            ],
        });

        function addRow(table, data = null) {
            if (table == 'table-pemasukan') {
                return $("#" + table + " tbody").append(
                    "<tr>" +
                    "<td> <button type='button' class='btn btn-xs btn-danger in' title='Hapus?' onclick='del(this)'> <span class='fa fa-trash'></span> </button> </td>" +
                    "<td><input type='text' class='form-control input-sm' name='pemasukan[]' value=''></td>" +
                    "<td><input type='text' class='form-control input-sm price' name='pemasukan_total[]' value='' onkeyup='jml()' style='text-align:right'></td>" +
                    "</tr>"
                );
            } else if (table == 'table-pengeluaran') {
                return $("#" + table + " tbody").append(
                    "<tr>" +
                    "<td> <button type='button' class='btn btn-xs btn-danger out' title='Hapus?' onclick='del(this)'> <span class='fa fa-trash'></span> </button> </td>" +
                    "<td><input type='text' class='form-control input-sm' name='pengeluaran[]' value=''> </td>" +
                    "<td><input type='text' class='form-control input-sm price nominal' name='pengeluaran_price[]' value='' onkeyup='sub(this)' style='text-align:right'> </td> " +
                    "<td><input type='text' class='form-control input-sm price qty' name='pengeluaran_qty[]' value='1' onkeyup='sub(this)' style='text-align:right'> </td> " +
                    "<td><input type='text' class='form-control input-sm total' name='pengeluaran_total[]' value=''readonly style='text-align:right'> </td>" +
                    "</tr>"
                );
            }
        }

        function jml(price = 0) {
            $('#table-pemasukan tr input.price').each(function () {
                price += toNumber($(this).val());
            });
            $('#jmlpem').val(toCurrency(price))
        }

        function jmlpeng(price = 0) {
            $('#table-pengeluaran tr input.total').each(function () {
                price += toNumber($(this).val());
            });

            $('#jmlpeng').val(toCurrency(price));
        }

        function sub(elem) {
            nominal = toNumber($(elem).closest('tr').find('td').find('.nominal').val());
            qty = toNumber($(elem).closest('tr').find('td').find('.qty').val());
            total = nominal * qty;
            $(elem).closest('tr').find('td').find('.total').val(toCurrency(total));

            jmlpeng();
        }

        function del(elem, type = null) {
            if (confirm('Hapus?')) {

                ($(elem).hasClass('in')) ? type = 'in': type = 'out';

                elem.closest('tr').remove();

                (type === 'out') ? total(): jml();
            }
        }

        function callBackData(data){
            $('#judul').val(data.judul);
            $('#note').val(data.note);
            $.each(data.budget_in,function(k,v){
                $('#table-pemasukan tbody').append(
                    "<tr>" +
                    "<td> <button type='button' class='btn btn-xs btn-danger in' title='Hapus?' onclick='del(this)'> <span class='fa fa-trash'></span> </button> </td>" +
                    "<td><input type='text' class='form-control input-sm' name='pemasukan[]' value='"+v.pemasukan+"'></td>" +
                    "<td><input type='text' class='form-control input-sm price' name='pemasukan_total[]' value='"+fixDec(v.pemasukan_total)+"' onkeyup='jml()' style='text-align:right'></td>" +
                    "</tr>"
                );

            });

            $.each(data.budget_out,function(k,v){
                $('#table-pengeluaran tbody').append(
                    "<tr>" +
                        "<td> <button type='button' class='btn btn-xs btn-danger out' title='Hapus?' onclick='del(this)'> <span class='fa fa-trash'></span> </button> </td>" +
                        "<td><input type='text' class='form-control input-sm' name='pengeluaran[]' value='"+v.pengeluaran+"'> </td>" +
                        "<td><input type='text' class='form-control input-sm price nominal' name='pengeluaran_price[]' value='"+fixDec(v.pengeluaran_price)+"' onkeyup='sub(this)' style='text-align:right'> </td> " +
                        "<td><input type='text' class='form-control input-sm price qty' name='pengeluaran_qty[]' value='"+v.pengeluaran_qty+"' onkeyup='sub(this)' style='text-align:right'> </td> " +
                        "<td><input type='text' class='form-control input-sm total' name='pengeluaran_total[]' value='"+fixDec(v.pengeluaran_total)+"'readonly style='text-align:right'> </td>" +
                    "</tr>"
                );
            });

            jml();
            jmlpeng();
        }

        function cekBalance() {
            var pem = toNumber($('#jmlpem').val());
            var peng = toNumber($('#jmlpeng').val());

            if(pem != peng){
                alert("Belum Balance");
                return false;
            }

            return true;
        }
    </script>
    @endsection